name: Build Cross-Platform App
on:
  # Permite declanșarea manuală din Actions
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build macOS dmg
        # Comanda jpackage pe o singură linie pentru a preveni erorile de shell (Invalid Option)
        run: jpackage --type dmg --input . --main-jar Christmas.jar --main-class Christmas.ChristmasApp --add-modules ALL-MODULE-PATH --name ChristmasApp

      - name: Upload dmg
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App
          path: "*.dmg"

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build Windows Installer (MSI)
        # Comanda jpackage pe o singură linie pentru a preveni erorile PowerShell (ParserError)
        run: jpackage --type msi --input . --main-jar Christmas.jar --main-class Christmas.ChristmasApp --add-modules ALL-MODULE-PATH --name ChristmasAppWin

      - name: Upload MSI
        uses: actions/upload-artifact@v4
        with:
          name: Windows-App
          path: "*.msi"
